export const ALL_CAMPAIGN_TYPES = [
  // META
  {
    id: "meta_leads",
    platform: "Meta",
    name: "Leads",
    tagline: "Collect contact info from interested people",
    description: "The Leads objective tells Meta's algorithm to find people most likely to submit a form — either a Meta Instant Form (no website needed) or a landing page form. Meta optimizes delivery toward people who have shown form-filling behavior.",
    whenToUse: "Use when your goal is to collect names, emails, or phone numbers from potential customers. Works best for service businesses, coaches, and consultants.",
    bestFor: "Local services, coaches, consultants, B2B, and anyone using a free consultation offer",
    notIdealFor: "Ecommerce with direct checkout, pure brand awareness plays, or low-budget impulse purchases",
    startingBudget: "$10–$20/day minimum",
  },
  {
    id: "meta_traffic",
    platform: "Meta",
    name: "Traffic",
    tagline: "Drive clicks to your website",
    description: "The Traffic objective optimizes for link clicks to your website. Meta finds people who are likely to click — but not necessarily buy or convert. This is a top-of-funnel play.",
    whenToUse: "Use for blog posts, content promotion, or building retargeting audiences. Not for direct response unless combined with strong pixel data.",
    bestFor: "Content promotion, building warm retargeting audiences, event pages",
    notIdealFor: "Lead generation, direct sales, or any conversion goal — you'll pay for clicks that don't convert",
    startingBudget: "$5–$10/day",
  },
  {
    id: "meta_engagement",
    platform: "Meta",
    name: "Engagement",
    tagline: "Maximize likes, comments, shares, and post saves",
    description: "The Engagement objective finds people most likely to interact with your post. This increases social proof and organic reach but doesn't directly generate leads or sales.",
    whenToUse: "Use to boost social proof on a post before launching a broader campaign, or for community building.",
    bestFor: "Boosting social proof, community building, growing page followers, product launches with strong organic content",
    notIdealFor: "Any direct response goal — engagement does not equal buyers",
    startingBudget: "$3–$5/day",
  },
  {
    id: "meta_awareness",
    platform: "Meta",
    name: "Awareness",
    tagline: "Put your brand in front of as many eyes as possible",
    description: "Awareness campaigns optimize for reach and impressions — showing your ad to as many unique people as possible. Meta won't optimize for any action, just exposure.",
    whenToUse: "Use for new brand launches, event promotion, or broad market education. Ideal when people need to hear about you multiple times before acting.",
    bestFor: "New brands, local businesses with mass appeal, event promotion, building a warm audience pool",
    notIdealFor: "Direct response, small budgets, or businesses that need immediate leads or sales",
    startingBudget: "$15–$30/day for meaningful reach",
  },
  {
    id: "meta_sales",
    platform: "Meta",
    name: "Sales",
    tagline: "Drive purchases directly from your ads",
    description: "The Sales objective (formerly Conversions) tells Meta to find people most likely to complete a purchase event on your website. Requires a properly configured Meta Pixel with purchase events firing.",
    whenToUse: "Use for ecommerce or any business with a strong website, pixel tracking, and a clear product for purchase.",
    bestFor: "Ecommerce stores, online courses, SaaS trials, any offer with direct online checkout",
    notIdealFor: "Businesses without a website, missing pixel setup, or no purchase conversion event configured",
    startingBudget: "$20–$50/day to get enough data for optimization",
  },
  {
    id: "meta_messages",
    platform: "Meta",
    name: "Messages",
    tagline: "Start conversations in Messenger, WhatsApp, or Instagram DMs",
    description: "The Messages objective drives people to start a conversation with your business via Messenger, WhatsApp, or Instagram Direct. Great for high-touch selling where a conversation closes the deal.",
    whenToUse: "Use when your sales process involves back-and-forth conversation, quote requests, or you want to qualify leads personally.",
    bestFor: "High-ticket services, real estate, custom products, markets where trust is built in conversation",
    notIdealFor: "Businesses that can't respond quickly or don't have a process for DM-based selling",
    startingBudget: "$10–$15/day",
  },
  {
    id: "meta_local",
    platform: "Meta",
    name: "Local Promotion",
    tagline: "Drive foot traffic and awareness in a specific location",
    description: "Local Promotion campaigns optimize for people who are near your physical location. They can include store traffic, call objectives, and geo-targeted reach to get nearby customers through your door.",
    whenToUse: "Use if you have a physical location and want people to come in — restaurants, gyms, salons, retail stores.",
    bestFor: "Restaurants, gyms, salons, retail, dentists, and any brick-and-mortar business",
    notIdealFor: "Online-only businesses or services without a fixed physical location",
    startingBudget: "$10–$20/day",
  },
  {
    id: "meta_retargeting",
    platform: "Meta",
    name: "Retargeting",
    tagline: "Re-engage people who already interacted with you",
    description: "Retargeting isn't a standalone Meta objective — it's an audience strategy layered onto Leads, Sales, or Traffic objectives. You target website visitors, video viewers, or lead form openers who didn't convert.",
    whenToUse: "Use when you have existing website traffic or audience data (minimum 1,000 people in the custom audience).",
    bestFor: "Warm audiences who visited a product page, watched a video, or opened a lead form but didn't complete it",
    notIdealFor: "New businesses with no traffic or audience data yet — build your audience first",
    startingBudget: "$5–$15/day (audiences are smaller, efficiency is higher)",
  },

  // GOOGLE
  {
    id: "google_search",
    platform: "Google",
    name: "Search",
    tagline: "Show ads when people search for what you offer",
    description: "Google Search campaigns show text ads when someone types a relevant keyword into Google. You only pay when someone clicks. This captures high-intent users who are actively looking for your product or service.",
    whenToUse: "Use when people are actively searching for your solution. Best for immediate-need services or established product categories.",
    bestFor: "Local services, emergency services, ecommerce with strong search volume, SaaS, B2B lead gen",
    notIdealFor: "New categories where people don't know to search yet, or very low-budget awareness goals",
    startingBudget: "$15–$30/day to gather enough click data",
  },
  {
    id: "google_pmax",
    platform: "Google",
    name: "Performance Max",
    tagline: "Let Google AI optimize across all of its channels at once",
    description: "Performance Max (PMax) is a single campaign type that serves across Search, Display, YouTube, Gmail, Maps, and Shopping. Google's AI allocates budget automatically across all channels to drive the most conversions.",
    whenToUse: "Use when you have solid conversion tracking, a Google Merchant Center feed (for ecommerce), or want Google to maximize conversion volume at scale.",
    bestFor: "Ecommerce with product feeds, businesses with strong conversion data, advertisers wanting full Google network coverage",
    notIdealFor: "Businesses without conversion tracking, those wanting granular control, or small budgets without enough conversion data",
    startingBudget: "$30–$50/day minimum for the algorithm to learn",
  },
  {
    id: "google_display",
    platform: "Google",
    name: "Display",
    tagline: "Show banner ads across millions of websites",
    description: "Google Display Network shows visual banner ads on millions of third-party websites, apps, and Gmail. It's a broad reach tool for awareness or retargeting, not direct lead gen.",
    whenToUse: "Use for brand awareness, retargeting website visitors, or keeping your brand visible during longer consideration phases.",
    bestFor: "Retargeting, brand awareness, low-CPM exposure, long sales cycle products",
    notIdealFor: "Direct lead generation, small local businesses, high-urgency offers that need immediate action",
    startingBudget: "$10–$20/day",
  },
  {
    id: "google_local",
    platform: "Google",
    name: "Local / Store Visit",
    tagline: "Drive foot traffic and calls to your physical location",
    description: "Local campaigns and Local Search ads show up in Google Search, Maps, and Display to drive calls, directions, and store visits. Google optimizes for people near your location.",
    whenToUse: "Use if you have a Google Business Profile and want nearby customers to find, call, or visit you.",
    bestFor: "Restaurants, gyms, salons, dental offices, retail, and any business with a physical location",
    notIdealFor: "Online-only businesses, national brands without locations, or lead gen without a physical address",
    startingBudget: "$10–$20/day",
  },
  {
    id: "google_call",
    platform: "Google",
    name: "Call Campaign",
    tagline: "Drive phone calls directly from your ad — no website needed",
    description: "Call-only campaigns show a phone number prominently in the ad. The ad's only action is to call — no website visits. Google optimizes for call volume.",
    whenToUse: "Use when a phone call is the ideal conversion and your business answers calls quickly. Great for emergency services.",
    bestFor: "Emergency services, local service businesses, healthcare, legal, and any business where calls close the deal",
    notIdealFor: "Businesses that can't answer phones reliably, ecommerce, or offers that need visual content to convert",
    startingBudget: "$15–$25/day",
  },
  {
    id: "google_remarketing",
    platform: "Google",
    name: "Remarketing",
    tagline: "Follow up with people who visited your website",
    description: "Google Remarketing (via Display or Search) targets past website visitors with tailored ads as they browse the web or search again on Google. It's one of the highest-converting campaign types when set up correctly.",
    whenToUse: "Use when you have website traffic but people aren't converting on the first visit. Requires Google Ads tag installed.",
    bestFor: "Ecommerce cart abandoners, service businesses with warm leads, SaaS trial conversion",
    notIdealFor: "New businesses with no website traffic, or businesses without a Google Ads tracking tag",
    startingBudget: "$5–$15/day (high-intent, efficient spend)",
  },
  {
    id: "google_youtube",
    platform: "Google",
    name: "YouTube",
    tagline: "Run skippable or non-skippable video ads on YouTube",
    description: "YouTube campaigns run video ads before or during YouTube videos. You can target by interest, demographics, search behavior, and even specific channels. Formats include skippable in-stream, bumper ads, and more.",
    whenToUse: "Use when you have video content and want to build brand awareness, educate an audience, or retarget viewers.",
    bestFor: "Brand storytelling, product demos, coaching/education, SaaS explainers, awareness for competitive markets",
    notIdealFor: "Businesses without video assets, very small budgets, or direct response campaigns without strong video content",
    startingBudget: "$15–$30/day",
  },
];