import { Link } from "react-router-dom";
import { Zap } from "lucide-react";

export default function Terms() {
  return (
    <div className="min-h-screen bg-[#0D1117] text-white">
      <nav className="border-b border-white/10 h-14 flex items-center justify-between px-4 sm:px-8">
        <Link to="/" className="flex items-center gap-2 font-bold text-sm">
          <div className="w-6 h-6 bg-[#E53E3E] rounded-md flex items-center justify-center">
            <Zap className="w-3.5 h-3.5 text-white" />
          </div>
          Fire-Works AI
        </Link>
      </nav>

      <div className="max-w-3xl mx-auto px-4 py-16 space-y-8">
        <div>
          <h1 className="text-3xl font-black text-white mb-2">Terms of Service</h1>
          <p className="text-white/40 text-sm">Last updated: May 2026 · Fire-Works Eco by Colonna Media</p>
        </div>

        {[
          {
            title: "1. Acceptance of Terms",
            body: `By accessing or using Fire-Works AI ("the Service"), operated by Fire-Works Eco by Colonna Media, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.`
          },
          {
            title: "2. Description of Service",
            body: `Fire-Works AI is an AI-powered ad copy generation tool that produces marketing content for Google Ads, Meta Ads, and organic social media posts. The Service is provided on a per-generation basis. Results are delivered digitally via on-screen display and email.`
          },
          {
            title: "3. Payments and Refunds",
            body: `All purchases are one-time payments processed securely through Stripe. Due to the digital and immediate nature of the Service — AI-generated content is produced and delivered upon payment — all sales are final and non-refundable. If you experience a technical issue that prevents delivery of your content, please contact us at colonnamedia@gmail.com and we will work to resolve it promptly.`
          },
          {
            title: "4. Use of Generated Content",
            body: `You retain full ownership of the ad copy and content generated for your business through the Service. You may use, modify, and publish the generated content for any lawful business purpose. Fire-Works Eco by Colonna Media does not claim ownership of content generated on your behalf.`
          },
          {
            title: "5. Acceptable Use",
            body: `You agree not to use the Service to generate content that is unlawful, deceptive, harassing, defamatory, or otherwise harmful. You are solely responsible for how you use the generated content in your advertising campaigns. Fire-Works Eco by Colonna Media is not responsible for the performance or outcome of any advertising campaigns you run using the generated content.`
          },
          {
            title: "6. AI-Generated Content Disclaimer",
            body: `Content generated by the Service is produced by artificial intelligence and is provided as a starting point for your marketing efforts. While we strive for quality and relevance, we make no guarantees regarding the performance, accuracy, or suitability of any generated content for your specific business needs. Always review and edit generated content before publishing.`
          },
          {
            title: "7. Account and Data",
            body: `If you create an account, you are responsible for maintaining the confidentiality of your login credentials. We store your business profile information to provide a better experience on return visits. You may request deletion of your data at any time by contacting us at colonnamedia@gmail.com.`
          },
          {
            title: "8. Limitation of Liability",
            body: `To the fullest extent permitted by law, Fire-Works Eco by Colonna Media shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability shall not exceed the amount you paid for the specific generation that gave rise to the claim.`
          },
          {
            title: "9. Changes to Terms",
            body: `We reserve the right to update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the new Terms. We will update the "Last updated" date at the top of this page when changes are made.`
          },
          {
            title: "10. Contact",
            body: `For questions about these Terms, please contact us at colonnamedia@gmail.com or visit our Support page.`
          },
        ].map((section, i) => (
          <div key={i} className="space-y-2">
            <h2 className="text-base font-bold text-white">{section.title}</h2>
            <p className="text-sm text-white/60 leading-relaxed">{section.body}</p>
          </div>
        ))}

        <div className="pt-8 border-t border-white/10 flex gap-6 text-sm text-white/30">
          <Link to="/privacy" className="hover:text-white transition-colors">Privacy Policy</Link>
          <Link to="/support" className="hover:text-white transition-colors">Support</Link>
          <Link to="/" className="hover:text-white transition-colors">Home</Link>
        </div>
      </div>
    </div>
  );
}
